package com.shine.view.entity.bcs;
// Generated by Hibernate Tools 3.4.0.CR1



/**
 *功能
 */
public class UserRoles  implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	 public UserRoles() {
		    
	 }
	 

	/**
	*Name:id
	*Comment:
	*/
	 private Integer  id;
	/**
	*Name:userId
	*Comment:
	*/
	 private Integer  userId;
	/**
	*Name:resourceId
	*Comment:
	*/
	 private Integer  resourceId;
	/**
	*Name:role
	*Comment:
	*/
	 private String  role;
   

   
	/**
	*Name:id
	*Comment:
	*/
    public Integer getId() {
        return this.id;
    }
    
	/**
	*Name:id
	*Comment:
	*/
    public void setId(Integer id) {
        this.id = id;
    }
	/**
	*Name:userId
	*Comment:
	*/
    public Integer getUserId() {
        return this.userId;
    }
    
	/**
	*Name:userId
	*Comment:
	*/
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
	/**
	*Name:resourceId
	*Comment:
	*/
    public Integer getResourceId() {
        return this.resourceId;
    }
    
	/**
	*Name:resourceId
	*Comment:
	*/
    public void setResourceId(Integer resourceId) {
        this.resourceId = resourceId;
    }
	/**
	*Name:role
	*Comment:
	*/
    public String getRole() {
        return this.role;
    }
    
	/**
	*Name:role
	*Comment:
	*/
    public void setRole(String role) {
        this.role = role;
    }
    
}


