package com.shine.view.entity.bcs;
// Generated by Hibernate Tools 3.4.0.CR1



/**
 *功能
 */
public class Characteristics  implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	 public Characteristics() {
		    
	 }
	 

	/**
	*Name:id
	*Comment:
	*/
	 private Integer  id;
	/**
	*Name:kee
	*Comment:
	*/
	 private String  kee;
	/**
	*Name:name
	*Comment:
	*/
	 private String  name;
	/**
	*Name:ruleId
	*Comment:
	*/
	 private Integer  ruleId;
	/**
	*Name:characteristicOrder
	*Comment:
	*/
	 private Integer  characteristicOrder;
	/**
	*Name:enabled
	*Comment:
	*/
	 private Boolean  enabled;
	/**
	*Name:parentId
	*Comment:
	*/
	 private Integer  parentId;
	/**
	*Name:rootId
	*Comment:
	*/
	 private Integer  rootId;
	/**
	*Name:functionKey
	*Comment:
	*/
	 private String  functionKey;
	/**
	*Name:factorValue
	*Comment:
	*/
	 private java.math.BigDecimal  factorValue;
	/**
	*Name:factorUnit
	*Comment:
	*/
	 private String  factorUnit;
	/**
	*Name:offsetValue
	*Comment:
	*/
	 private java.math.BigDecimal  offsetValue;
	/**
	*Name:offsetUnit
	*Comment:
	*/
	 private String  offsetUnit;
	/**
	*Name:createdAt
	*Comment:
	*/
	 private java.util.Date  createdAt;
	/**
	*Name:updatedAt
	*Comment:
	*/
	 private java.util.Date  updatedAt;
   

   
	/**
	*Name:id
	*Comment:
	*/
    public Integer getId() {
        return this.id;
    }
    
	/**
	*Name:id
	*Comment:
	*/
    public void setId(Integer id) {
        this.id = id;
    }
	/**
	*Name:kee
	*Comment:
	*/
    public String getKee() {
        return this.kee;
    }
    
	/**
	*Name:kee
	*Comment:
	*/
    public void setKee(String kee) {
        this.kee = kee;
    }
	/**
	*Name:name
	*Comment:
	*/
    public String getName() {
        return this.name;
    }
    
	/**
	*Name:name
	*Comment:
	*/
    public void setName(String name) {
        this.name = name;
    }
	/**
	*Name:ruleId
	*Comment:
	*/
    public Integer getRuleId() {
        return this.ruleId;
    }
    
	/**
	*Name:ruleId
	*Comment:
	*/
    public void setRuleId(Integer ruleId) {
        this.ruleId = ruleId;
    }
	/**
	*Name:characteristicOrder
	*Comment:
	*/
    public Integer getCharacteristicOrder() {
        return this.characteristicOrder;
    }
    
	/**
	*Name:characteristicOrder
	*Comment:
	*/
    public void setCharacteristicOrder(Integer characteristicOrder) {
        this.characteristicOrder = characteristicOrder;
    }
	/**
	*Name:enabled
	*Comment:
	*/
    public Boolean getEnabled() {
        return this.enabled;
    }
    
	/**
	*Name:enabled
	*Comment:
	*/
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }
	/**
	*Name:parentId
	*Comment:
	*/
    public Integer getParentId() {
        return this.parentId;
    }
    
	/**
	*Name:parentId
	*Comment:
	*/
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }
	/**
	*Name:rootId
	*Comment:
	*/
    public Integer getRootId() {
        return this.rootId;
    }
    
	/**
	*Name:rootId
	*Comment:
	*/
    public void setRootId(Integer rootId) {
        this.rootId = rootId;
    }
	/**
	*Name:functionKey
	*Comment:
	*/
    public String getFunctionKey() {
        return this.functionKey;
    }
    
	/**
	*Name:functionKey
	*Comment:
	*/
    public void setFunctionKey(String functionKey) {
        this.functionKey = functionKey;
    }
	/**
	*Name:factorValue
	*Comment:
	*/
    public java.math.BigDecimal getFactorValue() {
        return this.factorValue;
    }
    
	/**
	*Name:factorValue
	*Comment:
	*/
    public void setFactorValue(java.math.BigDecimal factorValue) {
        this.factorValue = factorValue;
    }
	/**
	*Name:factorUnit
	*Comment:
	*/
    public String getFactorUnit() {
        return this.factorUnit;
    }
    
	/**
	*Name:factorUnit
	*Comment:
	*/
    public void setFactorUnit(String factorUnit) {
        this.factorUnit = factorUnit;
    }
	/**
	*Name:offsetValue
	*Comment:
	*/
    public java.math.BigDecimal getOffsetValue() {
        return this.offsetValue;
    }
    
	/**
	*Name:offsetValue
	*Comment:
	*/
    public void setOffsetValue(java.math.BigDecimal offsetValue) {
        this.offsetValue = offsetValue;
    }
	/**
	*Name:offsetUnit
	*Comment:
	*/
    public String getOffsetUnit() {
        return this.offsetUnit;
    }
    
	/**
	*Name:offsetUnit
	*Comment:
	*/
    public void setOffsetUnit(String offsetUnit) {
        this.offsetUnit = offsetUnit;
    }
	/**
	*Name:createdAt
	*Comment:
	*/
    public java.util.Date getCreatedAt() {
        return this.createdAt;
    }
    
	/**
	*Name:createdAt
	*Comment:
	*/
    public void setCreatedAt(java.util.Date createdAt) {
        this.createdAt = createdAt;
    }
	/**
	*Name:updatedAt
	*Comment:
	*/
    public java.util.Date getUpdatedAt() {
        return this.updatedAt;
    }
    
	/**
	*Name:updatedAt
	*Comment:
	*/
    public void setUpdatedAt(java.util.Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    
}


