package com.shine.view.entity.bcs;
// Generated by Hibernate Tools 3.4.0.CR1



/**
 *功能
 */
public class GroupsUsers  implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	 public GroupsUsers() {
		    
	 }
	 

	/**
	*Name:userId
	*Comment:
	*/
	 private Integer  userId;
	/**
	*Name:groupId
	*Comment:
	*/
	 private Integer  groupId;
   

   
	/**
	*Name:userId
	*Comment:
	*/
    public Integer getUserId() {
        return this.userId;
    }
    
	/**
	*Name:userId
	*Comment:
	*/
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
	/**
	*Name:groupId
	*Comment:
	*/
    public Integer getGroupId() {
        return this.groupId;
    }
    
	/**
	*Name:groupId
	*Comment:
	*/
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }
    
}


