package com.shine.view.entity.bcs;
// Generated by Hibernate Tools 3.4.0.CR1



/**
 *功能
 */
public class LoadedTemplates  implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	 public LoadedTemplates() {
		    
	 }
	 

	/**
	*Name:id
	*Comment:
	*/
	 private Integer  id;
	/**
	*Name:kee
	*Comment:
	*/
	 private String  kee;
	/**
	*Name:templateType
	*Comment:
	*/
	 private String  templateType;
   

   
	/**
	*Name:id
	*Comment:
	*/
    public Integer getId() {
        return this.id;
    }
    
	/**
	*Name:id
	*Comment:
	*/
    public void setId(Integer id) {
        this.id = id;
    }
	/**
	*Name:kee
	*Comment:
	*/
    public String getKee() {
        return this.kee;
    }
    
	/**
	*Name:kee
	*Comment:
	*/
    public void setKee(String kee) {
        this.kee = kee;
    }
	/**
	*Name:templateType
	*Comment:
	*/
    public String getTemplateType() {
        return this.templateType;
    }
    
	/**
	*Name:templateType
	*Comment:
	*/
    public void setTemplateType(String templateType) {
        this.templateType = templateType;
    }
    
}


