package com.shine.view.entity.bcs;
// Generated by Hibernate Tools 3.4.0.CR1



/**
 *功能
 */
public class PermTemplatesGroups  implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	 public PermTemplatesGroups() {
		    
	 }
	 

	/**
	*Name:id
	*Comment:
	*/
	 private Integer  id;
	/**
	*Name:groupId
	*Comment:
	*/
	 private Integer  groupId;
	/**
	*Name:templateId
	*Comment:
	*/
	 private Integer  templateId;
	/**
	*Name:permissionReference
	*Comment:
	*/
	 private String  permissionReference;
	/**
	*Name:createdAt
	*Comment:
	*/
	 private java.util.Date  createdAt;
	/**
	*Name:updatedAt
	*Comment:
	*/
	 private java.util.Date  updatedAt;
   

   
	/**
	*Name:id
	*Comment:
	*/
    public Integer getId() {
        return this.id;
    }
    
	/**
	*Name:id
	*Comment:
	*/
    public void setId(Integer id) {
        this.id = id;
    }
	/**
	*Name:groupId
	*Comment:
	*/
    public Integer getGroupId() {
        return this.groupId;
    }
    
	/**
	*Name:groupId
	*Comment:
	*/
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }
	/**
	*Name:templateId
	*Comment:
	*/
    public Integer getTemplateId() {
        return this.templateId;
    }
    
	/**
	*Name:templateId
	*Comment:
	*/
    public void setTemplateId(Integer templateId) {
        this.templateId = templateId;
    }
	/**
	*Name:permissionReference
	*Comment:
	*/
    public String getPermissionReference() {
        return this.permissionReference;
    }
    
	/**
	*Name:permissionReference
	*Comment:
	*/
    public void setPermissionReference(String permissionReference) {
        this.permissionReference = permissionReference;
    }
	/**
	*Name:createdAt
	*Comment:
	*/
    public java.util.Date getCreatedAt() {
        return this.createdAt;
    }
    
	/**
	*Name:createdAt
	*Comment:
	*/
    public void setCreatedAt(java.util.Date createdAt) {
        this.createdAt = createdAt;
    }
	/**
	*Name:updatedAt
	*Comment:
	*/
    public java.util.Date getUpdatedAt() {
        return this.updatedAt;
    }
    
	/**
	*Name:updatedAt
	*Comment:
	*/
    public void setUpdatedAt(java.util.Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    
}


