package com.shine.view.entity.bcs;
// Generated by Hibernate Tools 3.4.0.CR1



/**
 *功能
 */
public class ProjectLinks  implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	 public ProjectLinks() {
		    
	 }
	 

	/**
	*Name:id
	*Comment:
	*/
	 private Integer  id;
	/**
	*Name:linkType
	*Comment:
	*/
	 private String  linkType;
	/**
	*Name:name
	*Comment:
	*/
	 private String  name;
	/**
	*Name:href
	*Comment:
	*/
	 private String  href;
	/**
	*Name:componentUuid
	*Comment:
	*/
	 private String  componentUuid;
   

   
	/**
	*Name:id
	*Comment:
	*/
    public Integer getId() {
        return this.id;
    }
    
	/**
	*Name:id
	*Comment:
	*/
    public void setId(Integer id) {
        this.id = id;
    }
	/**
	*Name:linkType
	*Comment:
	*/
    public String getLinkType() {
        return this.linkType;
    }
    
	/**
	*Name:linkType
	*Comment:
	*/
    public void setLinkType(String linkType) {
        this.linkType = linkType;
    }
	/**
	*Name:name
	*Comment:
	*/
    public String getName() {
        return this.name;
    }
    
	/**
	*Name:name
	*Comment:
	*/
    public void setName(String name) {
        this.name = name;
    }
	/**
	*Name:href
	*Comment:
	*/
    public String getHref() {
        return this.href;
    }
    
	/**
	*Name:href
	*Comment:
	*/
    public void setHref(String href) {
        this.href = href;
    }
	/**
	*Name:componentUuid
	*Comment:
	*/
    public String getComponentUuid() {
        return this.componentUuid;
    }
    
	/**
	*Name:componentUuid
	*Comment:
	*/
    public void setComponentUuid(String componentUuid) {
        this.componentUuid = componentUuid;
    }
    
}


