package com.shine.view.entity.bcs;
// Generated by Hibernate Tools 3.4.0.CR1



/**
 *功能
 */
public class Projects  implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	 public Projects() {
		    
	 }
	 

	/**
	*Name:id
	*Comment:
	*/
	 private Integer  id;
	/**
	*Name:name
	*Comment:
	*/
	 private String  name;
	/**
	*Name:description
	*Comment:
	*/
	 private String  description;
	/**
	*Name:enabled
	*Comment:
	*/
	 private Boolean  enabled;
	/**
	*Name:scope
	*Comment:
	*/
	 private String  scope;
	/**
	*Name:qualifier
	*Comment:
	*/
	 private String  qualifier;
	/**
	*Name:kee
	*Comment:
	*/
	 private String  kee;
	/**
	*Name:rootId
	*Comment:
	*/
	 private Integer  rootId;
	/**
	*Name:language
	*Comment:
	*/
	 private String  language;
	/**
	*Name:copyResourceId
	*Comment:
	*/
	 private Integer  copyResourceId;
	/**
	*Name:longName
	*Comment:
	*/
	 private String  longName;
	/**
	*Name:personId
	*Comment:
	*/
	 private Integer  personId;
	/**
	*Name:createdAt
	*Comment:
	*/
	 private java.util.Date  createdAt;
	/**
	*Name:path
	*Comment:
	*/
	 private String  path;
	/**
	*Name:deprecatedKee
	*Comment:
	*/
	 private String  deprecatedKee;
	/**
	*Name:uuid
	*Comment:
	*/
	 private String  uuid;
	/**
	*Name:projectUuid
	*Comment:
	*/
	 private String  projectUuid;
	/**
	*Name:moduleUuid
	*Comment:
	*/
	 private String  moduleUuid;
	/**
	*Name:moduleUuidPath
	*Comment:
	*/
	 private String  moduleUuidPath;
	/**
	*Name:authorizationUpdatedAt
	*Comment:
	*/
	 private Long  authorizationUpdatedAt;
   

   
	/**
	*Name:id
	*Comment:
	*/
    public Integer getId() {
        return this.id;
    }
    
	/**
	*Name:id
	*Comment:
	*/
    public void setId(Integer id) {
        this.id = id;
    }
	/**
	*Name:name
	*Comment:
	*/
    public String getName() {
        return this.name;
    }
    
	/**
	*Name:name
	*Comment:
	*/
    public void setName(String name) {
        this.name = name;
    }
	/**
	*Name:description
	*Comment:
	*/
    public String getDescription() {
        return this.description;
    }
    
	/**
	*Name:description
	*Comment:
	*/
    public void setDescription(String description) {
        this.description = description;
    }
	/**
	*Name:enabled
	*Comment:
	*/
    public Boolean getEnabled() {
        return this.enabled;
    }
    
	/**
	*Name:enabled
	*Comment:
	*/
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }
	/**
	*Name:scope
	*Comment:
	*/
    public String getScope() {
        return this.scope;
    }
    
	/**
	*Name:scope
	*Comment:
	*/
    public void setScope(String scope) {
        this.scope = scope;
    }
	/**
	*Name:qualifier
	*Comment:
	*/
    public String getQualifier() {
        return this.qualifier;
    }
    
	/**
	*Name:qualifier
	*Comment:
	*/
    public void setQualifier(String qualifier) {
        this.qualifier = qualifier;
    }
	/**
	*Name:kee
	*Comment:
	*/
    public String getKee() {
        return this.kee;
    }
    
	/**
	*Name:kee
	*Comment:
	*/
    public void setKee(String kee) {
        this.kee = kee;
    }
	/**
	*Name:rootId
	*Comment:
	*/
    public Integer getRootId() {
        return this.rootId;
    }
    
	/**
	*Name:rootId
	*Comment:
	*/
    public void setRootId(Integer rootId) {
        this.rootId = rootId;
    }
	/**
	*Name:language
	*Comment:
	*/
    public String getLanguage() {
        return this.language;
    }
    
	/**
	*Name:language
	*Comment:
	*/
    public void setLanguage(String language) {
        this.language = language;
    }
	/**
	*Name:copyResourceId
	*Comment:
	*/
    public Integer getCopyResourceId() {
        return this.copyResourceId;
    }
    
	/**
	*Name:copyResourceId
	*Comment:
	*/
    public void setCopyResourceId(Integer copyResourceId) {
        this.copyResourceId = copyResourceId;
    }
	/**
	*Name:longName
	*Comment:
	*/
    public String getLongName() {
        return this.longName;
    }
    
	/**
	*Name:longName
	*Comment:
	*/
    public void setLongName(String longName) {
        this.longName = longName;
    }
	/**
	*Name:personId
	*Comment:
	*/
    public Integer getPersonId() {
        return this.personId;
    }
    
	/**
	*Name:personId
	*Comment:
	*/
    public void setPersonId(Integer personId) {
        this.personId = personId;
    }
	/**
	*Name:createdAt
	*Comment:
	*/
    public java.util.Date getCreatedAt() {
        return this.createdAt;
    }
    
	/**
	*Name:createdAt
	*Comment:
	*/
    public void setCreatedAt(java.util.Date createdAt) {
        this.createdAt = createdAt;
    }
	/**
	*Name:path
	*Comment:
	*/
    public String getPath() {
        return this.path;
    }
    
	/**
	*Name:path
	*Comment:
	*/
    public void setPath(String path) {
        this.path = path;
    }
	/**
	*Name:deprecatedKee
	*Comment:
	*/
    public String getDeprecatedKee() {
        return this.deprecatedKee;
    }
    
	/**
	*Name:deprecatedKee
	*Comment:
	*/
    public void setDeprecatedKee(String deprecatedKee) {
        this.deprecatedKee = deprecatedKee;
    }
	/**
	*Name:uuid
	*Comment:
	*/
    public String getUuid() {
        return this.uuid;
    }
    
	/**
	*Name:uuid
	*Comment:
	*/
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }
	/**
	*Name:projectUuid
	*Comment:
	*/
    public String getProjectUuid() {
        return this.projectUuid;
    }
    
	/**
	*Name:projectUuid
	*Comment:
	*/
    public void setProjectUuid(String projectUuid) {
        this.projectUuid = projectUuid;
    }
	/**
	*Name:moduleUuid
	*Comment:
	*/
    public String getModuleUuid() {
        return this.moduleUuid;
    }
    
	/**
	*Name:moduleUuid
	*Comment:
	*/
    public void setModuleUuid(String moduleUuid) {
        this.moduleUuid = moduleUuid;
    }
	/**
	*Name:moduleUuidPath
	*Comment:
	*/
    public String getModuleUuidPath() {
        return this.moduleUuidPath;
    }
    
	/**
	*Name:moduleUuidPath
	*Comment:
	*/
    public void setModuleUuidPath(String moduleUuidPath) {
        this.moduleUuidPath = moduleUuidPath;
    }
	/**
	*Name:authorizationUpdatedAt
	*Comment:
	*/
    public Long getAuthorizationUpdatedAt() {
        return this.authorizationUpdatedAt;
    }
    
	/**
	*Name:authorizationUpdatedAt
	*Comment:
	*/
    public void setAuthorizationUpdatedAt(Long authorizationUpdatedAt) {
        this.authorizationUpdatedAt = authorizationUpdatedAt;
    }
    
}


