package com.shine.view.entity.bcs;
// Generated by Hibernate Tools 3.4.0.CR1



/**
 *功能
 */
public class RulesParameters  implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	 public RulesParameters() {
		    
	 }
	 

	/**
	*Name:id
	*Comment:
	*/
	 private Integer  id;
	/**
	*Name:ruleId
	*Comment:
	*/
	 private Integer  ruleId;
	/**
	*Name:name
	*Comment:
	*/
	 private String  name;
	/**
	*Name:description
	*Comment:
	*/
	 private String  description;
	/**
	*Name:paramType
	*Comment:
	*/
	 private String  paramType;
	/**
	*Name:defaultValue
	*Comment:
	*/
	 private String  defaultValue;
   

   
	/**
	*Name:id
	*Comment:
	*/
    public Integer getId() {
        return this.id;
    }
    
	/**
	*Name:id
	*Comment:
	*/
    public void setId(Integer id) {
        this.id = id;
    }
	/**
	*Name:ruleId
	*Comment:
	*/
    public Integer getRuleId() {
        return this.ruleId;
    }
    
	/**
	*Name:ruleId
	*Comment:
	*/
    public void setRuleId(Integer ruleId) {
        this.ruleId = ruleId;
    }
	/**
	*Name:name
	*Comment:
	*/
    public String getName() {
        return this.name;
    }
    
	/**
	*Name:name
	*Comment:
	*/
    public void setName(String name) {
        this.name = name;
    }
	/**
	*Name:description
	*Comment:
	*/
    public String getDescription() {
        return this.description;
    }
    
	/**
	*Name:description
	*Comment:
	*/
    public void setDescription(String description) {
        this.description = description;
    }
	/**
	*Name:paramType
	*Comment:
	*/
    public String getParamType() {
        return this.paramType;
    }
    
	/**
	*Name:paramType
	*Comment:
	*/
    public void setParamType(String paramType) {
        this.paramType = paramType;
    }
	/**
	*Name:defaultValue
	*Comment:
	*/
    public String getDefaultValue() {
        return this.defaultValue;
    }
    
	/**
	*Name:defaultValue
	*Comment:
	*/
    public void setDefaultValue(String defaultValue) {
        this.defaultValue = defaultValue;
    }
    
}


