package com.shine.view.entity.bcs;
// Generated by Hibernate Tools 3.4.0.CR1



/**
 *功能
 */
public class Widgets  implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	 public Widgets() {
		    
	 }
	 

	/**
	*Name:id
	*Comment:
	*/
	 private Integer  id;
	/**
	*Name:dashboardId
	*Comment:
	*/
	 private Integer  dashboardId;
	/**
	*Name:widgetKey
	*Comment:
	*/
	 private String  widgetKey;
	/**
	*Name:name
	*Comment:
	*/
	 private String  name;
	/**
	*Name:description
	*Comment:
	*/
	 private String  description;
	/**
	*Name:columnIndex
	*Comment:
	*/
	 private Integer  columnIndex;
	/**
	*Name:rowIndex
	*Comment:
	*/
	 private Integer  rowIndex;
	/**
	*Name:configured
	*Comment:
	*/
	 private Boolean  configured;
	/**
	*Name:createdAt
	*Comment:
	*/
	 private java.util.Date  createdAt;
	/**
	*Name:updatedAt
	*Comment:
	*/
	 private java.util.Date  updatedAt;
	/**
	*Name:resourceId
	*Comment:
	*/
	 private Integer  resourceId;
   

   
	/**
	*Name:id
	*Comment:
	*/
    public Integer getId() {
        return this.id;
    }
    
	/**
	*Name:id
	*Comment:
	*/
    public void setId(Integer id) {
        this.id = id;
    }
	/**
	*Name:dashboardId
	*Comment:
	*/
    public Integer getDashboardId() {
        return this.dashboardId;
    }
    
	/**
	*Name:dashboardId
	*Comment:
	*/
    public void setDashboardId(Integer dashboardId) {
        this.dashboardId = dashboardId;
    }
	/**
	*Name:widgetKey
	*Comment:
	*/
    public String getWidgetKey() {
        return this.widgetKey;
    }
    
	/**
	*Name:widgetKey
	*Comment:
	*/
    public void setWidgetKey(String widgetKey) {
        this.widgetKey = widgetKey;
    }
	/**
	*Name:name
	*Comment:
	*/
    public String getName() {
        return this.name;
    }
    
	/**
	*Name:name
	*Comment:
	*/
    public void setName(String name) {
        this.name = name;
    }
	/**
	*Name:description
	*Comment:
	*/
    public String getDescription() {
        return this.description;
    }
    
	/**
	*Name:description
	*Comment:
	*/
    public void setDescription(String description) {
        this.description = description;
    }
	/**
	*Name:columnIndex
	*Comment:
	*/
    public Integer getColumnIndex() {
        return this.columnIndex;
    }
    
	/**
	*Name:columnIndex
	*Comment:
	*/
    public void setColumnIndex(Integer columnIndex) {
        this.columnIndex = columnIndex;
    }
	/**
	*Name:rowIndex
	*Comment:
	*/
    public Integer getRowIndex() {
        return this.rowIndex;
    }
    
	/**
	*Name:rowIndex
	*Comment:
	*/
    public void setRowIndex(Integer rowIndex) {
        this.rowIndex = rowIndex;
    }
	/**
	*Name:configured
	*Comment:
	*/
    public Boolean getConfigured() {
        return this.configured;
    }
    
	/**
	*Name:configured
	*Comment:
	*/
    public void setConfigured(Boolean configured) {
        this.configured = configured;
    }
	/**
	*Name:createdAt
	*Comment:
	*/
    public java.util.Date getCreatedAt() {
        return this.createdAt;
    }
    
	/**
	*Name:createdAt
	*Comment:
	*/
    public void setCreatedAt(java.util.Date createdAt) {
        this.createdAt = createdAt;
    }
	/**
	*Name:updatedAt
	*Comment:
	*/
    public java.util.Date getUpdatedAt() {
        return this.updatedAt;
    }
    
	/**
	*Name:updatedAt
	*Comment:
	*/
    public void setUpdatedAt(java.util.Date updatedAt) {
        this.updatedAt = updatedAt;
    }
	/**
	*Name:resourceId
	*Comment:
	*/
    public Integer getResourceId() {
        return this.resourceId;
    }
    
	/**
	*Name:resourceId
	*Comment:
	*/
    public void setResourceId(Integer resourceId) {
        this.resourceId = resourceId;
    }
    
}


