package com.shine.view.entity.bcs;
// Generated by Hibernate Tools 3.4.0.CR1



/**
 *功能
 */
public class CeActivity  implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	 public CeActivity() {
		    
	 }
	 

	/**
	*Name:id
	*Comment:
	*/
	 private Integer  id;
	/**
	*Name:uuid
	*Comment:
	*/
	 private String  uuid;
	/**
	*Name:taskType
	*Comment:
	*/
	 private String  taskType;
	/**
	*Name:componentUuid
	*Comment:
	*/
	 private String  componentUuid;
	/**
	*Name:status
	*Comment:
	*/
	 private String  status;
	/**
	*Name:isLast
	*Comment:
	*/
	 private Boolean  isLast;
	/**
	*Name:isLastKey
	*Comment:
	*/
	 private String  isLastKey;
	/**
	*Name:submitterLogin
	*Comment:
	*/
	 private String  submitterLogin;
	/**
	*Name:submittedAt
	*Comment:
	*/
	 private Long  submittedAt;
	/**
	*Name:startedAt
	*Comment:
	*/
	 private Long  startedAt;
	/**
	*Name:executedAt
	*Comment:
	*/
	 private Long  executedAt;
	/**
	*Name:createdAt
	*Comment:
	*/
	 private Long  createdAt;
	/**
	*Name:updatedAt
	*Comment:
	*/
	 private Long  updatedAt;
	/**
	*Name:executionTimeMs
	*Comment:
	*/
	 private Long  executionTimeMs;
	/**
	*Name:snapshotId
	*Comment:
	*/
	 private Long  snapshotId;
   

   
	/**
	*Name:id
	*Comment:
	*/
    public Integer getId() {
        return this.id;
    }
    
	/**
	*Name:id
	*Comment:
	*/
    public void setId(Integer id) {
        this.id = id;
    }
	/**
	*Name:uuid
	*Comment:
	*/
    public String getUuid() {
        return this.uuid;
    }
    
	/**
	*Name:uuid
	*Comment:
	*/
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }
	/**
	*Name:taskType
	*Comment:
	*/
    public String getTaskType() {
        return this.taskType;
    }
    
	/**
	*Name:taskType
	*Comment:
	*/
    public void setTaskType(String taskType) {
        this.taskType = taskType;
    }
	/**
	*Name:componentUuid
	*Comment:
	*/
    public String getComponentUuid() {
        return this.componentUuid;
    }
    
	/**
	*Name:componentUuid
	*Comment:
	*/
    public void setComponentUuid(String componentUuid) {
        this.componentUuid = componentUuid;
    }
	/**
	*Name:status
	*Comment:
	*/
    public String getStatus() {
        return this.status;
    }
    
	/**
	*Name:status
	*Comment:
	*/
    public void setStatus(String status) {
        this.status = status;
    }
	/**
	*Name:isLast
	*Comment:
	*/
    public Boolean getIsLast() {
        return this.isLast;
    }
    
	/**
	*Name:isLast
	*Comment:
	*/
    public void setIsLast(Boolean isLast) {
        this.isLast = isLast;
    }
	/**
	*Name:isLastKey
	*Comment:
	*/
    public String getIsLastKey() {
        return this.isLastKey;
    }
    
	/**
	*Name:isLastKey
	*Comment:
	*/
    public void setIsLastKey(String isLastKey) {
        this.isLastKey = isLastKey;
    }
	/**
	*Name:submitterLogin
	*Comment:
	*/
    public String getSubmitterLogin() {
        return this.submitterLogin;
    }
    
	/**
	*Name:submitterLogin
	*Comment:
	*/
    public void setSubmitterLogin(String submitterLogin) {
        this.submitterLogin = submitterLogin;
    }
	/**
	*Name:submittedAt
	*Comment:
	*/
    public Long getSubmittedAt() {
        return this.submittedAt;
    }
    
	/**
	*Name:submittedAt
	*Comment:
	*/
    public void setSubmittedAt(Long submittedAt) {
        this.submittedAt = submittedAt;
    }
	/**
	*Name:startedAt
	*Comment:
	*/
    public Long getStartedAt() {
        return this.startedAt;
    }
    
	/**
	*Name:startedAt
	*Comment:
	*/
    public void setStartedAt(Long startedAt) {
        this.startedAt = startedAt;
    }
	/**
	*Name:executedAt
	*Comment:
	*/
    public Long getExecutedAt() {
        return this.executedAt;
    }
    
	/**
	*Name:executedAt
	*Comment:
	*/
    public void setExecutedAt(Long executedAt) {
        this.executedAt = executedAt;
    }
	/**
	*Name:createdAt
	*Comment:
	*/
    public Long getCreatedAt() {
        return this.createdAt;
    }
    
	/**
	*Name:createdAt
	*Comment:
	*/
    public void setCreatedAt(Long createdAt) {
        this.createdAt = createdAt;
    }
	/**
	*Name:updatedAt
	*Comment:
	*/
    public Long getUpdatedAt() {
        return this.updatedAt;
    }
    
	/**
	*Name:updatedAt
	*Comment:
	*/
    public void setUpdatedAt(Long updatedAt) {
        this.updatedAt = updatedAt;
    }
	/**
	*Name:executionTimeMs
	*Comment:
	*/
    public Long getExecutionTimeMs() {
        return this.executionTimeMs;
    }
    
	/**
	*Name:executionTimeMs
	*Comment:
	*/
    public void setExecutionTimeMs(Long executionTimeMs) {
        this.executionTimeMs = executionTimeMs;
    }
	/**
	*Name:snapshotId
	*Comment:
	*/
    public Long getSnapshotId() {
        return this.snapshotId;
    }
    
	/**
	*Name:snapshotId
	*Comment:
	*/
    public void setSnapshotId(Long snapshotId) {
        this.snapshotId = snapshotId;
    }
    
}


