package com.shine.view.entity.bcs;
// Generated by Hibernate Tools 3.4.0.CR1



/**
 *功能
 */
public class Events  implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	 public Events() {
		    
	 }
	 

	/**
	*Name:id
	*Comment:
	*/
	 private Integer  id;
	/**
	*Name:name
	*Comment:
	*/
	 private String  name;
	/**
	*Name:snapshotId
	*Comment:
	*/
	 private Integer  snapshotId;
	/**
	*Name:category
	*Comment:
	*/
	 private String  category;
	/**
	*Name:description
	*Comment:
	*/
	 private String  description;
	/**
	*Name:eventData
	*Comment:
	*/
	 private String  eventData;
	/**
	*Name:eventDate
	*Comment:
	*/
	 private Long  eventDate;
	/**
	*Name:createdAt
	*Comment:
	*/
	 private Long  createdAt;
	/**
	*Name:componentUuid
	*Comment:
	*/
	 private String  componentUuid;
   

   
	/**
	*Name:id
	*Comment:
	*/
    public Integer getId() {
        return this.id;
    }
    
	/**
	*Name:id
	*Comment:
	*/
    public void setId(Integer id) {
        this.id = id;
    }
	/**
	*Name:name
	*Comment:
	*/
    public String getName() {
        return this.name;
    }
    
	/**
	*Name:name
	*Comment:
	*/
    public void setName(String name) {
        this.name = name;
    }
	/**
	*Name:snapshotId
	*Comment:
	*/
    public Integer getSnapshotId() {
        return this.snapshotId;
    }
    
	/**
	*Name:snapshotId
	*Comment:
	*/
    public void setSnapshotId(Integer snapshotId) {
        this.snapshotId = snapshotId;
    }
	/**
	*Name:category
	*Comment:
	*/
    public String getCategory() {
        return this.category;
    }
    
	/**
	*Name:category
	*Comment:
	*/
    public void setCategory(String category) {
        this.category = category;
    }
	/**
	*Name:description
	*Comment:
	*/
    public String getDescription() {
        return this.description;
    }
    
	/**
	*Name:description
	*Comment:
	*/
    public void setDescription(String description) {
        this.description = description;
    }
	/**
	*Name:eventData
	*Comment:
	*/
    public String getEventData() {
        return this.eventData;
    }
    
	/**
	*Name:eventData
	*Comment:
	*/
    public void setEventData(String eventData) {
        this.eventData = eventData;
    }
	/**
	*Name:eventDate
	*Comment:
	*/
    public Long getEventDate() {
        return this.eventDate;
    }
    
	/**
	*Name:eventDate
	*Comment:
	*/
    public void setEventDate(Long eventDate) {
        this.eventDate = eventDate;
    }
	/**
	*Name:createdAt
	*Comment:
	*/
    public Long getCreatedAt() {
        return this.createdAt;
    }
    
	/**
	*Name:createdAt
	*Comment:
	*/
    public void setCreatedAt(Long createdAt) {
        this.createdAt = createdAt;
    }
	/**
	*Name:componentUuid
	*Comment:
	*/
    public String getComponentUuid() {
        return this.componentUuid;
    }
    
	/**
	*Name:componentUuid
	*Comment:
	*/
    public void setComponentUuid(String componentUuid) {
        this.componentUuid = componentUuid;
    }
    
}


