package com.shine.view.entity.bcs;
// Generated by Hibernate Tools 3.4.0.CR1



/**
 *功能
 */
public class Rules  implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	 public Rules() {
		    
	 }
	 

	/**
	*Name:id
	*Comment:
	*/
	 private Integer  id;
	/**
	*Name:name
	*Comment:
	*/
	 private String  name;
	/**
	*Name:pluginRuleKey
	*Comment:
	*/
	 private String  pluginRuleKey;
	/**
	*Name:pluginConfigKey
	*Comment:
	*/
	 private String  pluginConfigKey;
	/**
	*Name:pluginName
	*Comment:
	*/
	 private String  pluginName;
	/**
	*Name:description
	*Comment:
	*/
	 private String  description;
	/**
	*Name:priority
	*Comment:
	*/
	 private Integer  priority;
	/**
	*Name:templateId
	*Comment:
	*/
	 private Integer  templateId;
	/**
	*Name:status
	*Comment:
	*/
	 private String  status;
	/**
	*Name:language
	*Comment:
	*/
	 private String  language;
	/**
	*Name:createdAt
	*Comment:
	*/
	 private java.util.Date  createdAt;
	/**
	*Name:updatedAt
	*Comment:
	*/
	 private java.util.Date  updatedAt;
	/**
	*Name:noteCreatedAt
	*Comment:
	*/
	 private java.util.Date  noteCreatedAt;
	/**
	*Name:noteUpdatedAt
	*Comment:
	*/
	 private java.util.Date  noteUpdatedAt;
	/**
	*Name:noteUserLogin
	*Comment:
	*/
	 private String  noteUserLogin;
	/**
	*Name:noteData
	*Comment:
	*/
	 private String  noteData;
	/**
	*Name:characteristicId
	*Comment:
	*/
	 private Integer  characteristicId;
	/**
	*Name:defaultCharacteristicId
	*Comment:
	*/
	 private Integer  defaultCharacteristicId;
	/**
	*Name:remediationFunction
	*Comment:
	*/
	 private String  remediationFunction;
	/**
	*Name:defaultRemediationFunction
	*Comment:
	*/
	 private String  defaultRemediationFunction;
	/**
	*Name:remediationCoeff
	*Comment:
	*/
	 private String  remediationCoeff;
	/**
	*Name:defaultRemediationCoeff
	*Comment:
	*/
	 private String  defaultRemediationCoeff;
	/**
	*Name:remediationOffset
	*Comment:
	*/
	 private String  remediationOffset;
	/**
	*Name:defaultRemediationOffset
	*Comment:
	*/
	 private String  defaultRemediationOffset;
	/**
	*Name:effortToFixDescription
	*Comment:
	*/
	 private String  effortToFixDescription;
	/**
	*Name:tags
	*Comment:
	*/
	 private String  tags;
	/**
	*Name:systemTags
	*Comment:
	*/
	 private String  systemTags;
	/**
	*Name:isTemplate
	*Comment:
	*/
	 private Boolean  isTemplate;
	/**
	*Name:descriptionFormat
	*Comment:
	*/
	 private String  descriptionFormat;
   

   
	/**
	*Name:id
	*Comment:
	*/
    public Integer getId() {
        return this.id;
    }
    
	/**
	*Name:id
	*Comment:
	*/
    public void setId(Integer id) {
        this.id = id;
    }
	/**
	*Name:name
	*Comment:
	*/
    public String getName() {
        return this.name;
    }
    
	/**
	*Name:name
	*Comment:
	*/
    public void setName(String name) {
        this.name = name;
    }
	/**
	*Name:pluginRuleKey
	*Comment:
	*/
    public String getPluginRuleKey() {
        return this.pluginRuleKey;
    }
    
	/**
	*Name:pluginRuleKey
	*Comment:
	*/
    public void setPluginRuleKey(String pluginRuleKey) {
        this.pluginRuleKey = pluginRuleKey;
    }
	/**
	*Name:pluginConfigKey
	*Comment:
	*/
    public String getPluginConfigKey() {
        return this.pluginConfigKey;
    }
    
	/**
	*Name:pluginConfigKey
	*Comment:
	*/
    public void setPluginConfigKey(String pluginConfigKey) {
        this.pluginConfigKey = pluginConfigKey;
    }
	/**
	*Name:pluginName
	*Comment:
	*/
    public String getPluginName() {
        return this.pluginName;
    }
    
	/**
	*Name:pluginName
	*Comment:
	*/
    public void setPluginName(String pluginName) {
        this.pluginName = pluginName;
    }
	/**
	*Name:description
	*Comment:
	*/
    public String getDescription() {
        return this.description;
    }
    
	/**
	*Name:description
	*Comment:
	*/
    public void setDescription(String description) {
        this.description = description;
    }
	/**
	*Name:priority
	*Comment:
	*/
    public Integer getPriority() {
        return this.priority;
    }
    
	/**
	*Name:priority
	*Comment:
	*/
    public void setPriority(Integer priority) {
        this.priority = priority;
    }
	/**
	*Name:templateId
	*Comment:
	*/
    public Integer getTemplateId() {
        return this.templateId;
    }
    
	/**
	*Name:templateId
	*Comment:
	*/
    public void setTemplateId(Integer templateId) {
        this.templateId = templateId;
    }
	/**
	*Name:status
	*Comment:
	*/
    public String getStatus() {
        return this.status;
    }
    
	/**
	*Name:status
	*Comment:
	*/
    public void setStatus(String status) {
        this.status = status;
    }
	/**
	*Name:language
	*Comment:
	*/
    public String getLanguage() {
        return this.language;
    }
    
	/**
	*Name:language
	*Comment:
	*/
    public void setLanguage(String language) {
        this.language = language;
    }
	/**
	*Name:createdAt
	*Comment:
	*/
    public java.util.Date getCreatedAt() {
        return this.createdAt;
    }
    
	/**
	*Name:createdAt
	*Comment:
	*/
    public void setCreatedAt(java.util.Date createdAt) {
        this.createdAt = createdAt;
    }
	/**
	*Name:updatedAt
	*Comment:
	*/
    public java.util.Date getUpdatedAt() {
        return this.updatedAt;
    }
    
	/**
	*Name:updatedAt
	*Comment:
	*/
    public void setUpdatedAt(java.util.Date updatedAt) {
        this.updatedAt = updatedAt;
    }
	/**
	*Name:noteCreatedAt
	*Comment:
	*/
    public java.util.Date getNoteCreatedAt() {
        return this.noteCreatedAt;
    }
    
	/**
	*Name:noteCreatedAt
	*Comment:
	*/
    public void setNoteCreatedAt(java.util.Date noteCreatedAt) {
        this.noteCreatedAt = noteCreatedAt;
    }
	/**
	*Name:noteUpdatedAt
	*Comment:
	*/
    public java.util.Date getNoteUpdatedAt() {
        return this.noteUpdatedAt;
    }
    
	/**
	*Name:noteUpdatedAt
	*Comment:
	*/
    public void setNoteUpdatedAt(java.util.Date noteUpdatedAt) {
        this.noteUpdatedAt = noteUpdatedAt;
    }
	/**
	*Name:noteUserLogin
	*Comment:
	*/
    public String getNoteUserLogin() {
        return this.noteUserLogin;
    }
    
	/**
	*Name:noteUserLogin
	*Comment:
	*/
    public void setNoteUserLogin(String noteUserLogin) {
        this.noteUserLogin = noteUserLogin;
    }
	/**
	*Name:noteData
	*Comment:
	*/
    public String getNoteData() {
        return this.noteData;
    }
    
	/**
	*Name:noteData
	*Comment:
	*/
    public void setNoteData(String noteData) {
        this.noteData = noteData;
    }
	/**
	*Name:characteristicId
	*Comment:
	*/
    public Integer getCharacteristicId() {
        return this.characteristicId;
    }
    
	/**
	*Name:characteristicId
	*Comment:
	*/
    public void setCharacteristicId(Integer characteristicId) {
        this.characteristicId = characteristicId;
    }
	/**
	*Name:defaultCharacteristicId
	*Comment:
	*/
    public Integer getDefaultCharacteristicId() {
        return this.defaultCharacteristicId;
    }
    
	/**
	*Name:defaultCharacteristicId
	*Comment:
	*/
    public void setDefaultCharacteristicId(Integer defaultCharacteristicId) {
        this.defaultCharacteristicId = defaultCharacteristicId;
    }
	/**
	*Name:remediationFunction
	*Comment:
	*/
    public String getRemediationFunction() {
        return this.remediationFunction;
    }
    
	/**
	*Name:remediationFunction
	*Comment:
	*/
    public void setRemediationFunction(String remediationFunction) {
        this.remediationFunction = remediationFunction;
    }
	/**
	*Name:defaultRemediationFunction
	*Comment:
	*/
    public String getDefaultRemediationFunction() {
        return this.defaultRemediationFunction;
    }
    
	/**
	*Name:defaultRemediationFunction
	*Comment:
	*/
    public void setDefaultRemediationFunction(String defaultRemediationFunction) {
        this.defaultRemediationFunction = defaultRemediationFunction;
    }
	/**
	*Name:remediationCoeff
	*Comment:
	*/
    public String getRemediationCoeff() {
        return this.remediationCoeff;
    }
    
	/**
	*Name:remediationCoeff
	*Comment:
	*/
    public void setRemediationCoeff(String remediationCoeff) {
        this.remediationCoeff = remediationCoeff;
    }
	/**
	*Name:defaultRemediationCoeff
	*Comment:
	*/
    public String getDefaultRemediationCoeff() {
        return this.defaultRemediationCoeff;
    }
    
	/**
	*Name:defaultRemediationCoeff
	*Comment:
	*/
    public void setDefaultRemediationCoeff(String defaultRemediationCoeff) {
        this.defaultRemediationCoeff = defaultRemediationCoeff;
    }
	/**
	*Name:remediationOffset
	*Comment:
	*/
    public String getRemediationOffset() {
        return this.remediationOffset;
    }
    
	/**
	*Name:remediationOffset
	*Comment:
	*/
    public void setRemediationOffset(String remediationOffset) {
        this.remediationOffset = remediationOffset;
    }
	/**
	*Name:defaultRemediationOffset
	*Comment:
	*/
    public String getDefaultRemediationOffset() {
        return this.defaultRemediationOffset;
    }
    
	/**
	*Name:defaultRemediationOffset
	*Comment:
	*/
    public void setDefaultRemediationOffset(String defaultRemediationOffset) {
        this.defaultRemediationOffset = defaultRemediationOffset;
    }
	/**
	*Name:effortToFixDescription
	*Comment:
	*/
    public String getEffortToFixDescription() {
        return this.effortToFixDescription;
    }
    
	/**
	*Name:effortToFixDescription
	*Comment:
	*/
    public void setEffortToFixDescription(String effortToFixDescription) {
        this.effortToFixDescription = effortToFixDescription;
    }
	/**
	*Name:tags
	*Comment:
	*/
    public String getTags() {
        return this.tags;
    }
    
	/**
	*Name:tags
	*Comment:
	*/
    public void setTags(String tags) {
        this.tags = tags;
    }
	/**
	*Name:systemTags
	*Comment:
	*/
    public String getSystemTags() {
        return this.systemTags;
    }
    
	/**
	*Name:systemTags
	*Comment:
	*/
    public void setSystemTags(String systemTags) {
        this.systemTags = systemTags;
    }
	/**
	*Name:isTemplate
	*Comment:
	*/
    public Boolean getIsTemplate() {
        return this.isTemplate;
    }
    
	/**
	*Name:isTemplate
	*Comment:
	*/
    public void setIsTemplate(Boolean isTemplate) {
        this.isTemplate = isTemplate;
    }
	/**
	*Name:descriptionFormat
	*Comment:
	*/
    public String getDescriptionFormat() {
        return this.descriptionFormat;
    }
    
	/**
	*Name:descriptionFormat
	*Comment:
	*/
    public void setDescriptionFormat(String descriptionFormat) {
        this.descriptionFormat = descriptionFormat;
    }
    
}


