package com.shine.view.entity.bcs;
// Generated by Hibernate Tools 3.4.0.CR1



/**
 *功能
 */
public class CeQueue  implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	 public CeQueue() {
		    
	 }
	 

	/**
	*Name:id
	*Comment:
	*/
	 private Integer  id;
	/**
	*Name:uuid
	*Comment:
	*/
	 private String  uuid;
	/**
	*Name:taskType
	*Comment:
	*/
	 private String  taskType;
	/**
	*Name:componentUuid
	*Comment:
	*/
	 private String  componentUuid;
	/**
	*Name:status
	*Comment:
	*/
	 private String  status;
	/**
	*Name:submitterLogin
	*Comment:
	*/
	 private String  submitterLogin;
	/**
	*Name:startedAt
	*Comment:
	*/
	 private Long  startedAt;
	/**
	*Name:createdAt
	*Comment:
	*/
	 private Long  createdAt;
	/**
	*Name:updatedAt
	*Comment:
	*/
	 private Long  updatedAt;
   

   
	/**
	*Name:id
	*Comment:
	*/
    public Integer getId() {
        return this.id;
    }
    
	/**
	*Name:id
	*Comment:
	*/
    public void setId(Integer id) {
        this.id = id;
    }
	/**
	*Name:uuid
	*Comment:
	*/
    public String getUuid() {
        return this.uuid;
    }
    
	/**
	*Name:uuid
	*Comment:
	*/
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }
	/**
	*Name:taskType
	*Comment:
	*/
    public String getTaskType() {
        return this.taskType;
    }
    
	/**
	*Name:taskType
	*Comment:
	*/
    public void setTaskType(String taskType) {
        this.taskType = taskType;
    }
	/**
	*Name:componentUuid
	*Comment:
	*/
    public String getComponentUuid() {
        return this.componentUuid;
    }
    
	/**
	*Name:componentUuid
	*Comment:
	*/
    public void setComponentUuid(String componentUuid) {
        this.componentUuid = componentUuid;
    }
	/**
	*Name:status
	*Comment:
	*/
    public String getStatus() {
        return this.status;
    }
    
	/**
	*Name:status
	*Comment:
	*/
    public void setStatus(String status) {
        this.status = status;
    }
	/**
	*Name:submitterLogin
	*Comment:
	*/
    public String getSubmitterLogin() {
        return this.submitterLogin;
    }
    
	/**
	*Name:submitterLogin
	*Comment:
	*/
    public void setSubmitterLogin(String submitterLogin) {
        this.submitterLogin = submitterLogin;
    }
	/**
	*Name:startedAt
	*Comment:
	*/
    public Long getStartedAt() {
        return this.startedAt;
    }
    
	/**
	*Name:startedAt
	*Comment:
	*/
    public void setStartedAt(Long startedAt) {
        this.startedAt = startedAt;
    }
	/**
	*Name:createdAt
	*Comment:
	*/
    public Long getCreatedAt() {
        return this.createdAt;
    }
    
	/**
	*Name:createdAt
	*Comment:
	*/
    public void setCreatedAt(Long createdAt) {
        this.createdAt = createdAt;
    }
	/**
	*Name:updatedAt
	*Comment:
	*/
    public Long getUpdatedAt() {
        return this.updatedAt;
    }
    
	/**
	*Name:updatedAt
	*Comment:
	*/
    public void setUpdatedAt(Long updatedAt) {
        this.updatedAt = updatedAt;
    }
    
}


